### ISSUE TITLE
Cannot get API Key

### ISSUE THREAD

**Issue by houseofbugs** [joshjcarrier/homeassistant-litter-robot#1]
Is there any way to pull the API key? I cannot locate it in the mobile app.

**Comment by joshjcarrier** [comment]
Looks like with their latest app update this login method has changed -- I'll revisit the implementaiton and see if the API key is still needed

**Comment by purebenwoo** [comment]
+1 Trying out your home assistant component, but can't find the API key.

**Comment by joshjcarrier** [comment]
Check out https://community.smartthings.com/t/litter-robot-connect/106882/18
