### ISSUE TITLE
status update is rather slow

### ISSUE THREAD

**Issue by SonomaGTS** [joshjcarrier/homeassistant-litter-robot#12]
Does this component update every 30 seconds like the default for HA? Or is it something else? I noticed when I trigger the cycle command it's almost instant but the status and the waste status and even night light are severely delayed. Is there a way to increase the polling?

**Comment by SonomaGTS** [comment]
So after a little more poking around I finally found this [timeout](https://github.com/joshjcarrier/homeassistant-litter-robot/blob/9464be533bcd20098ca7052ecdea465814b9be85/custom_components/litter_robot/__init__.py#L154-L158) which seems to resolve part of the issue however I am not sure what the negative impact is reducing that timeout will have for the litter robot api. The default state polling in HA is every 30 seconds so ireduced that 5 min Throttle down to 30 seconds and so far not ran into a snag. Seemed to have updated the status of the little robot relatively quick for initializing a clean cycle but took a little long to reset back to ready but I think that's the slowness of the api getting the update from the litter robot.

**Comment by NightShaman** [comment]
I agree, I set mine to 30 seconds as well, and it seems better. Especially when using a dashboard app to display status.

**Comment by joshjcarrier** [comment]
Cool is 30 sec the norm for these polling sensors? I can adjust that.

For the cycle reset I'll have to see if mine does the same thing

**Comment by SonomaGTS** [comment]
well it's been over a month and not ran into any snags. it's still not perfect but it catches the state changes even if delayed sometimes. Downside of having to fetch the status of the LR remotely from the api after it's updated remotely to the LR. Too bad there is no local api to bypass the cloud entirely.
