### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by DallasWonder** [joshjcarrier/homeassistant-litter-robot#13]
Does this custom component work with Home Assistant Community Store? https://github.com/hacs/integration

**Comment by DallasWonder** [comment]
NVM, there is a custom repository setting within HACS that looks like it handles this.

Thanks!

**Comment by JamieP83** [comment]
hey, how did you add this to HACS sorry?

**Comment by DallasWonder** [comment]
Install HACS, then go to the HACS component in the hassio GUI. In the HACS
component, there is a tab to add custom repositories. Select Integration
type and enter the GitHub URL for a hassio module (e.g.,
https://github.com/joshjcarrier/homeassistant-litter-robot)
