### ISSUE TITLE
Litterrobot integration not polling

### ISSUE THREAD

**Issue by mra282** [joshjcarrier/homeassistant-litter-robot#18]
Litter robot integration stopped polling at regular intervals as of latest Homeassistant version. At server start it will get status from bot but after it will not update.

HA version: 0.111.2

**Comment by Yazzcat** [comment]
First of all, thanks for this amazing integration. I love it.

I confirm I have the same issue that it only polls the waste on startup. The status seems to updat fine. If I trigger it from within the app on my android phone, I see (with a bit of delay) the status changing to cycling and later back to ready. However Night Light and Waste do not change, only on (re)start of Home Assistant (v0.111.4)
 
Thanks for looking into this!

**Comment by joshjcarrier** [comment]
Yep, something changed with this later Home Assistant -- I haven't updated so I didn't see the problem yet. I'll have to try upgrading again, my Raspberry Pi wasn't too happy last time.

Reading into the docs/example, the new way looks something like [this](https://github.com/home-assistant/core/blob/dev/homeassistant/components/github/sensor.py#L41) and is probably going to be more configurable (e.g. support #17 !)

https://developers.home-assistant.io/docs/integration_fetching_data#separate-polling-for-each-individual-entity

**Comment by joshjcarrier** [comment]
Can you give https://github.com/joshjcarrier/homeassistant-litter-robot/tree/fix/polling a spin? I just upgraded to 0.111.4 so I'll test this change for a bit.

**Comment by Yazzcat** [comment]
Dear Josh, thanks for looking into this. I will try it tonight. I did some debugging myself and is seems that all sensors are calling update_robots. But because this function is throttled, only the first call is returning the Json. Following calls are returning None. Thats why the status sensor is updated and the other sensors keep using the old json that was provided on startup of HA. I actually programmed a work around that seems to work for me, but I am very new to Python and have no experience whatsoever in custom components.I think it is better to go for your code.

**Comment by mra282** [comment]
I made the same change and removed the throttle. It still does not seem to update. I will pole around a bit more in the docs to see if there is something else that needs to be done besides adding scan_interval

**Comment by joshjcarrier** [comment]
@mra282 try out the new change in https://github.com/joshjcarrier/homeassistant-litter-robot/tree/fix/polling, I'm pretty sure I see it working for me.

I might try writing based on [this integration example](https://developers.home-assistant.io/docs/integration_fetching_data) and hope it'll be less prone to surprise breakage.

**Comment by mra282** [comment]
It's working now, thank you. Now my automation that casts to all my Google homes every minute to annoy me into emptying it works.

**Comment by joshjcarrier** [comment]
@mra282 if you have any tips/tricks/setup guides for something like that it'd be awesome to add to the readme!

**Comment by joshjcarrier** [comment]
Also if you have a moment, please try out this branch and see if everything works as expected, its basically a rewrite of how data is polled for HA 0.111:

https://github.com/joshjcarrier/homeassistant-litter-robot/tree/feat/data-update-coordinator

**Comment by mra282** [comment]
Will do. The automation I have to check status and annoy me to empty is built in node red. I am building one using hassio automation to do all the same. I will share once it works.
