### ISSUE TITLE
Empty /reset drawer

### ISSUE THREAD

**Issue by jacobhallgren** [joshjcarrier/homeassistant-litter-robot#21]
Hi, when will you be able to reset the drawer?

**Comment by joshjcarrier** [comment]
i’m testing out some pretty big code changes for HA 0.111 polling over in #20 , then right after that

**Comment by joshjcarrier** [comment]
i was also watching how the reset command works in the app and it sends a number like 46 or 22 to cycleCapacity, not totally sure yet where that number comes from

**Comment by joshjcarrier** [comment]
@jacobhallgren try this version https://github.com/joshjcarrier/homeassistant-litter-robot/tree/feat/reset-drawer from #22 . Update your configuration/groups.yaml as in the updated readme for the new command and let me know if everything works for you.

**Comment by jacobhallgren** [comment]
@joshjcarrier it worked! Thank you for the effort!
