### ISSUE TITLE
Why do you have it set to reset the drawer after every cycle?

### ISSUE THREAD

**Issue by julianrinaldi** [joshjcarrier/homeassistant-litter-robot#34]
In your code, you have the service "litter_robot.reset_drawer" set to run after every cleaning cycle. Why do you have it set like that, and is this correct? This is what happens when the litter_robot_reset_drawer switch is set to on when "{{ is_state('sensor.litter_robot_status', 'Clean Cycling') }}" correct?

Also, this is probably my favorite Home Assistant integration. I missed out on being able to use your referral code when buying the Litter-Robot, but please put a tip jar somewhere so I can send you some money!

**Comment by joshjcarrier** [comment]
I *think* that configuration tells the switch to change state based on the current status of the robot, so you can't trigger a reset while it is currently cycling. I'm open to better configurations -- feel free to recommend one with a pull request!
