### ISSUE TITLE
Version Number Required in manifest.json

### ISSUE THREAD

**Issue by benblustey** [joshjcarrier/homeassistant-litter-robot#43]
Home Assistant is now requiring a version number to be required for custom integrations.

https://developers.home-assistant.io/docs/creating_integration_manifest/#version

I've created a branch, just need permission to push.

**Comment by cchiapusio** [comment]
Here is the log entry:

`2021-05-23 10:55:30 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'litter_robot'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'litter_robot'`
