### ISSUE TITLE
Recently started to get an unexpected exception error.

### ISSUE THREAD

**Issue by julianrinaldi** [joshjcarrier/homeassistant-litter-robot#46]
Recently started getting the error below. I'm currently on 2021.10.2, and I believe it started happening once I upgraded to 2021.10.

```
This error originated from a custom integration.

Logger: custom_components.litter_robot.litter_robot
Source: custom_components/litter_robot/litter_robot.py:114
Integration: litter_robot (documentation)
First occurred: 7:00:13 PM (2 occurrences)
Last logged: 7:00:23 PM

[login] Unexpected exception: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

Here are my settings:

## System Health

version | core-2021.10.2
-- | --
installation_type | Home Assistant Core
dev | false
hassio | false
docker | false
user | homeassistant
virtualenv | true
python_version | 3.9.0
os_name | Darwin
os_version | 10.16
arch | x86_64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4326
Installed Version | 1.15.2
Stage | running
Available Repositories | 963
Installed Repositories | 104

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | October 16, 2021, 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | us-east-1-1.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 58
views | 26
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

```

**Comment by yyli** [comment]
@julianrinaldi I also ran into this, if you want to patch it yourself for now I made a PR https://github.com/joshjcarrier/homeassistant-litter-robot/pull/47 you can copy
