### ISSUE TITLE
x-api-key instruction is unclear

### ISSUE THREAD

**Issue by sstratoti** [joshjcarrier/homeassistant-litter-robot#7]
Hi Josh,

So it wasn't clear that you want us to copy the x-api-key value from the script mentioned in the forum post you added to the readme.
 
```
Gmdfw5Cq3F3Mk6xvvO0inHATJeoDv6C3KfwfOuh0
```
I thought you wanted us to copy and run that ST python script.

I copied and ran the python script you pointed to, and it produced a txt file with what I believed was my token (or api-key) and user_id. Tried to set up the component with that really long key, and it kept failing. It wasn't until I looked under the hood at your code and compared it to the forum post / python script that I realized that you wanted us to use the same x-api-key value from that ST forum post. Might want to clear that up in the readme? :)

Thanks for the work on this btw!

**Comment by joshjcarrier** [comment]
Thanks for the feedback! I'm open to accepting pull requests if you're good with words!

**Comment by joshjcarrier** [comment]
I think I'll just include the `x-api-key` in the instruction rather than having everyone jump through hoops to find it...
